<a href="https://colab.research.google.com/github/zhuofachen/collections/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
# from numpy import *

In [16]:
a = np.array([1,2,3,4])
b = np.array([[1, 2], [3, 4]])
print(a.size, b.size),  # The number of elements in the array is available through the ndarray.size property
print(shape(a), shape(b))
print(a.dtype, b.dtype)

4 4
(4,) (2, 2)
int64 int64


In [17]:
M = array([[1,2], [3,4]], dtype=complex)
print(M)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [24]:
x = arange(0, 10, 1)   # arguments: start, stop, step
x = arange(-1, 1, 0.1)
print(x)
x = linspace(0,10,25)
print(x)
x = logspace(0, 10, 10, base=e)
print(x)


[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]
[1.00000000e+00 3.03773178e+00 9.22781435e+00 2.80316249e+01
 8.51525577e+01 2.58670631e+02 7.85771994e+02 2.38696456e+03
 7.25095809e+03 2.20264658e+04]


In [29]:
x, y = mgrid[0:10, 0:5]
print(x,   y)


# print(x)
# print(x)
# print(x)
# print(x)
# print(x)
# print(x)
# print(x)
# print(x)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [6 6 6 6 6]
 [7 7 7 7 7]
 [8 8 8 8 8]
 [9 9 9 9 9]] [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [32]:
from numpy import random
x = random.rand(5,5) # uniform in [0, 1]
print(x)
x = random.randn(5,5)   # standard normal distributed random numbers
print(x)

[[0.97401198 0.51852871 0.88484357 0.29669426 0.37879458]
 [0.15373764 0.9602638  0.54155043 0.82306846 0.46197304]
 [0.81029127 0.46190423 0.51578397 0.91182665 0.82408952]
 [0.07802746 0.6952533  0.85789472 0.69456557 0.79504427]
 [0.94374655 0.13713917 0.02162795 0.65624679 0.78161459]]
[[-0.60494852 -0.4916956  -0.81329788  0.72728302 -1.81141708]
 [ 0.12204169  0.20013531  0.89458172 -0.90466987 -0.06050409]
 [ 0.57387947  1.39143654 -1.78506656  1.80843548 -0.05297378]
 [ 0.62622917 -0.56841636  0.0127683   1.71766259 -0.14834745]
 [ 1.22396657  0.84893154 -1.1364902   1.06989884  1.07807847]]


In [45]:
A =np.array([1,0.2,3,4,5])
print(A[1:3])
b = A * 2
print(b)
c = (A * 2 + 3)/2
print(c)

d = A * A
print(d)
A = 

[0.2 3. ]
[ 2.   0.4  6.   8.  10. ]
[2.5 1.7 4.5 5.5 6.5]
[ 1.    0.04  9.   16.   25.  ]


In [ ]:
# file io
save("random-matrix.npy", M)
savetxt("random-matrix.csv", M, fmt='%.5f') # fmt specifies the format
load("random-matrix.npy")

In [50]:
# Indexing:
A = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
print(A)
print(A[::2, ::2])
A[1:4, 1:4]

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [71]:
row_indices = [1, 2, 3]
column_indices = [1, 2, -1]
print(A[row_indices])
print(A[row_indices, column_indices])

mask = np.array([1, 0, 1, 0, 0], dtype=bool)
print(A[mask])  # this makes it easily later if we have condition evaluation, then pass the bool vector. 
x = arange(0, 10, 0.5)
mask = (5 < x) & (x < 7.5)
print(mask)
x[mask]


# take
v = arange(-3, 2)
row_indices = [1,3, 4]
print(v[row_indices])

v.take(row_indices)

# choose
which = [1, 0, 1, 0, 1]
choice = [[-2, -2, -2, -2, -2], [5,5,5,5,5]]
choose(which, choice)

[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
[11 22 34]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]
[False False False False False False False False False False False  True
  True  True  True False False False False False]
[-2  0  1]


array([ 5, -2,  5, -2,  5])

In [79]:
print(A)
v = arange(1, 6)
print(v)

print(A*v)   # element wise
print(v*v)
print(A * A) # element wise


[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[1 2 3 4 5]
[[  0   2   6  12  20]
 [ 10  22  36  52  70]
 [ 20  42  66  92 120]
 [ 30  62  96 132 170]
 [ 40  82 126 172 220]]
[ 1  4  9 16 25]
[[   0    1    4    9   16]
 [ 100  121  144  169  196]
 [ 400  441  484  529  576]
 [ 900  961 1024 1089 1156]
 [1600 1681 1764 1849 1936]]


In [83]:

# matrix multiplication. 
y = dot(A, A)
print(y)
y = dot(A, v)
print(y)
y = dot(v,v)
print(y)

[[ 300  310  320  330  340]
 [1300 1360 1420 1480 1540]
 [2300 2410 2520 2630 2740]
 [3300 3460 3620 3780 3940]
 [4300 4510 4720 4930 5140]]
[ 40 190 340 490 640]
55


In [87]:
# but if we cast the array to matrix, then we can use *  to do matrix multiplication

M = matrix(A)
v = matrix(v)
print(M*v)
print(v.T * v)

[[ 40]
 [190]
 [340]
 [490]
 [640]]
[[55]]


In [106]:
# data processing
print(A)
print(mean(A[:, 3]))
print(std(A[:, 3]))
print(var(A[:, 3]))
print(A.max())
print(A[:,3].max())
print(A[:,3].min())
print(A.max(axis = 0))
print(A.max(axis = 1))



[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
23.0
14.142135623730951
200.0
44
43
3
[40 41 42 43 44]
[ 4 14 24 34 44]
[[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [116]:
n, m = A.shape
print(A.reshape((1, n*m)))   # equals to A.flatten()
print(A)
b = np.array([0,0,0,0,0])
print(vstack((A, b)))

a = np.array([[1,2],[3,4]])

b = np.array([[0,0]])   # note at this point, b should be [[]], not []
print(a, b.T)
print(hstack((a, b.T)))

[[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [ 0  0  0  0  0]]
[[1 2]
 [3 4]] [[0]
 [0]]
[[1 2 0]
 [3 4 0]]


In [102]:
# cumsum and  prod, cumprod
d = arange(0, 10)
print(cumsum(d))
print(prod(d + 1))
print(cumprod(d + 1))

[ 0  1  3  6 10 15 21 28 36 45]
3628800
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [ ]:
# months = arange(1,13)
# monthly_mean = [mean(data[data[:,1] == month, 3]) for month in months]

In [119]:
#vectorize function


def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return 1 * (x >= 0)

print(Theta(array([-3,-2,-1,0,1,2,3])))
print(Theta(-1.2), Theta(2.6))

if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

[0 0 0 1 1 1 1]
0 1
at least one element in M is larger than 5
